AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for image-grayscale

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GrayscalingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageUri: 126720073631.dkr.ecr.us-west-2.amazonaws.com/grayscaler:latest
      Policies:
        - S3CrudPolicy:
            BucketName:
              Ref: destBucket
      Events:
        Grayscaling:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post
      Environment:
        Variables:
          BUCKET_NAME:
            Ref: destBucket
          RESULT_HANDLER_URL: https://webhook.site/77601984-54f2-4307-a720-99d8a19dfa7c
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./grayscaling
      DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GrayscalingFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Grayscaling function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/grayscaler/"
  GrayscalingFunctionFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt GrayscalingFunction.Arn
  GrayscalingFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GrayscalingFunctionRole.Arn

Parameters:
  destBucket:
    Type: String
    Description: Name of the S3 Bucket to put uploaded files into (must exist prior to deployment)
